# Generated by Django 3.1.7 on 2021-08-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('house_no', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=20)),
                ('rent_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SellList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('house_no', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=20)),
                ('sell_price', models.PositiveIntegerField()),
            ],
        ),
    ]
