# Generated by Django 3.1.7 on 2021-08-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_complain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain',
        ),
    ]
