# Generated by Django 3.1.7 on 2021-08-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_delete_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('mobile', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
            ],
        ),
    ]
