# Generated by Django 3.1.7 on 2021-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
