# Generated by Django 3.1.7 on 2021-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockno', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK'), ('4bhk', '4BHK')], default='2bhk', max_length=4)),
                ('detail', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='upload_house_imgs')),
            ],
        ),
    ]
