# Generated by Django 3.1.7 on 2021-07-25 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0003_auto_20210724_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateHouseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('mobile_no', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('house_id', models.PositiveIntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('members', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='allocate_house_detail')),
                ('entry_date', models.DateTimeField(default=datetime.date(2021, 7, 25))),
            ],
        ),
    ]
