# Generated by Django 3.1.7 on 2021-07-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0005_remove_allocatehousedetail_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societydetail',
            name='sname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
