# Generated by Django 3.1.7 on 2021-07-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0006_auto_20210730_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societydetail',
            name='sname',
            field=models.CharField(max_length=50),
        ),
    ]
