# Generated by Django 3.1.7 on 2021-08-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0007_auto_20210730_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatehousedetail',
            old_name='house_id',
            new_name='blockno',
        ),
    ]
