# Generated by Django 3.1.7 on 2021-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0009_auto_20210817_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatehousedetail',
            name='mobile_no',
            field=models.CharField(max_length=12),
        ),
    ]
