# Generated by Django 3.1.7 on 2021-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0010_auto_20210817_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatehousedetail',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
