# Generated by Django 3.1.7 on 2021-08-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0011_auto_20210817_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societydetail',
            name='sname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
