# Generated by Django 3.1.7 on 2021-10-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0012_auto_20210819_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatehousedetail',
            name='blockno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpart.housedetail'),
        ),
        migrations.AlterField(
            model_name='allocatehousedetail',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.societydetail'),
        ),
        migrations.AlterField(
            model_name='housedetail',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.societydetail'),
        ),
    ]
